server:
  port: 8010

spring:
  application:
    name: cloud-provider-payment-hystrix
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://42.194.220.29:3306/db2021?useUnicode=true&characterEncoding=utf-8&&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    #表示将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: payment8010
    prefer-ip-address: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.coder.springcloud.entities


